CREATE TABLE account (
  ACCOUNT_ID bigint(20) NOT NULL AUTO_INCREMENT,
  PASSWORD varchar(45) NOT NULL,
  NAME varchar(45) NOT NULL,
  EMAIL varchar(150) NULL,
  CREATED_DATE datetime NULL,
  UPDATE_DATE datetime NULL,
  PRIMARY KEY (ACCOUNT_ID),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE product (
  PRODUCT_ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  DESCRIPTION varchar(9000) NULL,
  CAT_ID bigint(20) NOT NULL,
  ACCOUNT_ID bigint(20) NOT NULL,
  CREATED_DATE datetime NOT NULL,
  UPDATE_DATE datetime NULL,
  INDEX CAT_IDX (CAT_ID),
  NDEX IDX_TAG (ACCOUNT_ID),
  CONSTRAINT CATPROD FOREIGN KEY (CAT_ID) REFERENCES category(CAT_ID) ON DELETE CASCADE ON UPDATE CASCADE
  CONSTRAINT CS_TAG FOREIGN KEY (ACCOUNT_ID) REFERENCES account(ACCOUNT_ID) ON DELETE CASCADE ON UPDATE CASCADE
  PRIMARY KEY (PRODUCT_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE category (
  CAT_ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  CREATED_DATE datetime NOT NULL,
  UPDATE_DATE datetime NULL,
  PRIMARY KEY (CAT_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE image (
  IMG_ID bigint(20) NOT NULL AUTO_INCREMENT,
  THUMBNAIL varchar(200) NOT NULL,
  URL varchar(200) NOT NULL,
  PRODUCT_ID bigint(20) NOT NULL,
  CREATED_DATE datetime NOT NULL,
  UPDATE_DATE datetime NULL,
  INDEX CAT_IDX (PRODUCT_ID),
  CONSTRAINT CATPROD FOREIGN KEY (PRODUCT_ID) REFERENCES product(PRODUCT_ID) ON DELETE CASCADE ON UPDATE CASCADE
  PRIMARY KEY (IMG_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;